FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env
WORKDIR /app

# Copy csproj and restore as distinct layers
COPY *.csproj .
RUN dotnet restore
# Copy everything else and build
COPY . .

ENV MONGO_DB=mongodb://localhost:27017

ENTRYPOINT ["dotnet", "test", "./UnitTests"]